### ISSUE TITLE
Player left after 5-10 seconds with no input...

### ISSUE THREAD

**Issue by Vytek** [lxndrdagreat/udp-unity-tests#1]
![schermata 2017-07-11 alle 11 55 45](https://user-images.githubusercontent.com/2614303/28063234-c4e66290-6630-11e7-986d-bc2380b9e77a.png)

After 5 seconds Player left, no heartbeat work :-( How can I fix this?

This project is very cool, I would like to use in 3D Project :-)

**Comment by lxndrdagreat** [comment]
I'm not sure if you were using the accompanying server project or not, but I noticed in its codebase that the heartbeat rate was at 10 seconds, while in the client code it was only sending the heartbeat every 30 seconds. This meant that if the player did not do any actions (movement), the server would never receive any messages and then kick that player for inactivity.

I've updated the server project to have a longer timeout rate, but you can also adjust the heartbeat setting in the client project to send more often.

I hope this helps solve your issue.

**Comment by Vytek** [comment]
Thank you for your note. Yes, I am using python server project!
